name: Build Docker Image
on: [push, pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/openpoker-dev/openpoker-backend
        tags:  |
          type=ref,enable=true,suffix=-{{sha}},event=tag
          type=ref,enable=true,suffix=-{{sha}},event=branch
          type=ref,enable=true,suffix=-{{sha}},event=pr
    - name: Login to Docker Registry Server
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/package/docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
